

# server config
server:
  port: 8002
  
# database config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url : jdbc:oracle:thin:@localhost:1521:xe
    username: C##THUNDER
    password: THUNDER
    
  mail:
    host: smtp.naver.com
    port: 465
    username: kbo0609@naver.com
    password: WZUTK12QFTCT
    properties:
     mail.smtp.auth: true
     mail.smtp.ssl.enable: true    

#file upload config
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\Users\리온\git\thunderbolts
  
      
#image upload directory F:/sub_project
image:
  image-dir: src/main/resources/upload/  
    
    
    
# mybatis congfig
mybatis:
  mapper-locations: mappers/**/*.xml
  
# log level (root 설정)
logging:
  level:
# root level - 전역 설정
    root: info
#package level - 지역 설정
    '[com.greedy.thunerbolts]': trace 
    
    
 